sudo: false
language: python
cache: pip
matrix:
  include:
    # - env: TOXENV=py35-lower_bound_deps
    #   python: 3.5
    # - env: TOXENV=py36-lower_bound_deps
    #   python: 3.6
    # - env: TOXENV=py37-lower_bound_deps
    #   python: 3.7
    #   sudo: required
    #   dist: xenial
    # - env: TOXENV=py35-upper_bound_deps
    #   python: 3.5
    # - env: TOXENV=py36-upper_bound_deps
    #   python: 3.6
    - env: TOXENV=py37
      python: 3.7
      sudo: required
      dist: xenial
install:
  - pip install tox coveralls
script:
  - make test-ci
after_success:
  - coveralls
notifications:
  email: false
