sudo: false
language: python
cache: pip
matrix:
  include:
    - env: TOXENV=py37
      python: 3.7
      sudo: required
      dist: xenial
install:
  - ./.githooks/deploy.sh
  - nvm install
  - npm ci
  - pip install -r requirements.txt
script:
  - make test-ci
after_success:
  - coveralls
notifications:
  email: false
